"""promocodes

Revision ID: ac1ddab41043
Revises: 6fc01183d296
Create Date: 2025-01-04 20:46:44.307524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from uuid import uuid4
from datetime import datetime

# revision identifiers, used by Alembic.
revision: str = 'ac1ddab41043'
down_revision: Union[str, None] = '6fc01183d296'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    promocodes_table = op.create_table('promocodes',
    sa.Column('promocode', sa.String(), nullable=True),
    sa.Column('discount_percent', sa.Float(), nullable=True),
    sa.Column('discount_rubles', sa.Float(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('usage_limit', sa.Integer(), nullable=True),
    sa.Column('used_count', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_one_time', sa.Boolean(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_promocodes_promocode'), 'promocodes', ['promocode'], unique=True)
    now = datetime.utcnow()

    base_promocodes = [
        {
            'id': str(uuid4()),
            'promocode': 'FREE-STANDARD-FOR-ONE-MONTH',
            'discount_percent': '0',
            'discount_rubles': '399',
            'usage_limit': 10,
            'used_cound': 0,
            'is_active': True,
            'created_at': now,
            'modified_at': now,
        },
        {
            'id': str(uuid4()),
            'promocode': 'MINUS-TEN-PERCENTS',
            'discount_percent': '10',
            'discount_rubles': '0',
            'usage_limit': 0,
            'used_cound': 0,
            'is_active': True,
            'created_at': now,
            'modified_at': now,
        },
        {
            'id': str(uuid4()),
            'promocode': 'MINUS100',
            'discount_percent': '0',
            'discount_rubles': '100',
            'usage_limit': 0,
            'used_cound': 0,
            'is_active': True,
            'created_at': now,
            'modified_at': now,
        },
    ]
    op.bulk_insert(promocodes_table, base_promocodes)


    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_promocodes_promocode'), table_name='promocodes')
    op.drop_table('promocodes')
    # ### end Alembic commands ###