version: '3'

services:

  search:
    build: search/app
    env_file:
      - ./.env
    restart: unless-stopped
    environment:
      - PROJECT_NAME=${PROJECT_NAME}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - ELASTIC_HOST=${ELASTIC_HOST}
      - ELASTIC_PORT=${ELASTIC_PORT}
    healthcheck:
      test: bash -c "exec 6<> /dev/tcp/localhost/8000"
      interval: 5s
      timeout: 3s
      retries: 20
    depends_on:
      elastic:
        condition: service_healthy
        restart: true
      redis:
        condition: service_healthy
        restart: true
