services:
  db:
      ports: !override
        - "15432:5432"
  elastic:
      ports: !override
        - "9200:9200"
  redis:
      ports: !override
        - "6379:6379"
  jaeger:
      ports: !override
        - "16686:16686"
